#This is workflow name
name: Hello Workflow

on:
  workflow_dispatch:

#These are jobs inside workflow
jobs:

#Name of the job
  greet:
  #This is the GithHub runner
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to user
        run: echo "Hello World"

      - name: Say hello to username
        run: echo "Hello $USER"
  #Name of Job
  details:
  #Every Job needs a runner
    runs-on: ubuntu-latest
    steps:
      - name: show what is the version of python
        run: docker --version && python --version   
