#Workflow Name
name: Portfolio 

#Workflow trigger
on: 
  push:
    branches: [main]
  workflow_dispatch: 
permissions:
  pages: write
  id-token: write

#Jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
        # acess the porttfolio code using pre-built actions
      - name: Checkout Code
        uses: actions/checkout@v4
        # set GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        # static code artifact
      - name: Upload static pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: .
        #deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
